version: "3"
services:
  fastapi:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=user
      - SQLITE_PATH=/sqlite.db
    volumes:
      - .:/data
      - ./db/sqlite.db:/sqlite.db
      - ./db:/code/sqlite.db

  # sqlite:
  #   image: nouchka/sqlite3
  #   environment:
  #     MYSQL_ROOT_PASSWORD: secret
  #     MYSQL_DATABASE: example
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - db:/bitnami/mongodb

# volumes:
#   db:

#version: '3'
#services:
#  app:
#    build: .
#    ports:
#      - "5000:80"
#    environment:
#      - SQLITE_PATH=/sqlite.db
#    env_file:
#      - .env
#    volumes:
#      - "./static:/app/app/static/"
#      - "./data/sqlite.db:/sqlite.db"